# Alacritty configuration
# Matching ghostty settings as closely as possible

[terminal]
shell = { program = "/home/andreym/.nix-profile/bin/nu" }

[window]
padding = { x = 4, y = 4 }
decorations = "Full"
dynamic_padding = false

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[cursor]
style = { shape = "Block", blinking = "Off" }

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

# Catppuccin Mocha theme
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.cursor]
text = "#11111b"
cursor = "#f5e0dc"

[colors.selection]
text = "#cdd6f4"
background = "#353749"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

# Keyboard bindings (matching ghostty where possible)
[[keyboard.bindings]]
key = "C"
mods = "Super"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Super"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Super|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Super|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "K"
mods = "Super"
action = "ClearHistory"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\n"
